# Generated by Django 2.2 on 2021-05-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tvshows_app', '0002_show_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
